[Automation] Adding vagrant files
EdDev/django-testing-tutorial pull request #8
Opened 2022-03-16 16:19 UTC by Yarboa

Adding django-pytest
Vagrant and Pipe files

2022-03-16 16:40 UTC, EdDev reviewed
Can we move all the files from the project root to a separated folder (e.g. `vagrant`)?

I prefer the base to be targeting containers (or self managed env) and as a companion for "backward compatibility" to have vagrant as an option.

WDYT?

2022-03-16 16:42 UTC, EdDev commented
Also, can you please change the commit message and the subject of the PR to something like: `env: Support deployment using Vagrant`

2022-03-16 17:07 UTC, Yarboa commented
> Also, can you please change the commit message and the subject of the PR to something like: `env: Support deployment using Vagrant`

:+1:

2022-03-16 17:08 UTC, Yarboa commented
> Can we move all the files from the project root to a separated folder (e.g. `vagrant`)?
> 
No need, for now

> I prefer the base to be targeting containers (or self managed env) and as a companion for "backward compatibility" to have vagrant as an option.
>

I will give it extra thought

> WDYT?

2022-09-06 14:56 UTC, Yarboa commented
Need to update README for vagrant

2022-09-06 16:45 UTC, Yarboa commented on README.vagrant.md
> +
Please delete, remains from previous readme?

2022-09-07 09:00 UTC, EdDev reviewed
Before I proceed in reading everything, I wanted to give a initial high level feedback.
I am fine with taking it without these points and then changing it myself, but if you have the time, it will be nicer.

- Currently the project does not use `pipenv`, for simplicity. But it is probably wrong and it makes sense to use it. So if you can add it in a separate PR/commit, it will be nice. We will not need this in this `vagrant` folder.
- The github action workflow will just require modification to align with the previous point. We will not need another one for sure.

Thank you very much for the investment and help in this!

2022-09-07 09:13 UTC, Yarboa commented
> Before I proceed in reading everything, I wanted to give a initial high level feedback. I am fine with taking it without these points and then changing it myself, but if you have the time, it will be nicer.
> 
> * Currently the project does not use `pipenv`, for simplicity. But it is probably wrong and it makes sense to use it. So if you can add it in a separate PR/commit, it will be nice. We will not need this in this `vagrant` folder.

You are correct,
But the IIUC the issue is look and feel from the students perspective,
We could add some comment related to pipenv, WDYT?

> * The github action workflow will just require modification to align with the previous point. We will not need another one for sure.
> 
> Thank you very much for the investment and help in this!

2022-09-07 10:00 UTC, EdDev commented on README.md
> +The project could be also targeted with Vagrant
Missing `.` at the end of the sentence.

2022-09-07 10:00 UTC, EdDev commented on README.md
> +- [vagrant](README.vagrant.md) [2]
`[2]` is suppose to point to a note?

2022-09-07 10:00 UTC, EdDev commented on README.vagrant.md
> +a tool that build and manage vms.
vms ==> `VM/s`

2022-09-07 10:42 UTC, Yarboa commented
ToDo,
Use export for Pipfile 
export PIPENV_PIPFILE=./vagrant/Pipfile
Instead of links. and it should be helpful with CI, also

2022-09-07 13:08 UTC, Yarboa commented on README.md
> +- [vagrant](README.vagrant.md) [2]
Ack

2022-09-07 13:08 UTC, Yarboa commented on README.vagrant.md
> +a tool that build and manage vms.
Ack

2022-09-07 13:08 UTC, Yarboa commented on README.md
> +The project could be also targeted with Vagrant
Ack

2022-09-22 08:27 UTC, EdDev requested changes
Thank you very much!
I had a few comments.

2nd commit: `[Updae to cloudbase fedora-36]`
Has a typo.

2022-09-22 08:27 UTC, EdDev commented on .github/workflows/check.yaml
> +      - name: Run flake8
I am unclear why the format job got changed.
It does not seem to be related to vagrant.

If we want to delve into details, it is not clear why we need to install all dependencies.
Also, the step is running `black` and not `flake8`.

2022-09-22 08:27 UTC, EdDev commented on README.md
> +The project could be also targeted with Vagrant.
> also targeted with

be deployed with

2022-09-22 08:27 UTC, EdDev commented on README.vagrant.md
> +Wait vagrant output as following:
Wait for the vagrant output to appear:

2022-09-22 08:27 UTC, EdDev commented on vagrant/app_setup.sh
> +mv /vagrant/requirements{.txt,}
Could you please explain in the commit message or here in a comment, why it is needed?

2022-09-22 11:57 UTC, Yarboa reviewed
@EdDev

2022-09-22 11:57 UTC, Yarboa commented on README.md
> +The project could be also targeted with Vagrant.
Ack

2022-09-22 11:57 UTC, Yarboa commented on README.vagrant.md
> +Wait vagrant output as following:
Ack

2022-09-22 11:57 UTC, Yarboa commented on vagrant/app_setup.sh
> +mv /vagrant/requirements{.txt,}
some, how even if am setting PIPENV PIPENV_PIPFILE=/vagrant/vagrant/Pipfile

once there is a call, using pipenv run python manage.py, 
pipenv find the requirements.txt under the directory and installing all the content of the file.

Maybe I should propose a MR to pipenv.
As per now, the container run with centos8 and python 3.8
on vagrant fedora-36 with python3.8


Please advise here, @EdDev 
Two oprions, 
* prepare the container with fedora-36 use the same python.
* research pipenv to understand automatic relation with requirements.txt and maybe propose a PR.

Third options somewhere in the middle
 
 
 I will try this solution also
 https://pipenv-fork.readthedocs.io/en/latest/basics.html#pipfile-lock-security-features

2022-09-22 11:57 UTC, Yarboa commented on .github/workflows/check.yaml
> +      - name: Run flake8
thanks for that, copy paste issues, sorry

2022-09-28 09:43 UTC, EdDev commented on vagrant/app_setup.sh
> +mv /vagrant/requirements{.txt,}
Thanks for the clarification.
I think we can work on this as a follow up, no need to block on it.

2022-09-28 09:44 UTC, EdDev submitted a review, later dismissed
Thank you!

If you do not mind, It would be nice to squash all the commits. Some are fixing prev commits issues.

2022-09-28 10:00 UTC, EdDev approved these changes
Great! Thank you.

2022-09-28 10:01 UTC, merged